# container-based build
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.11.8

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
  - sbt dist

after_success: 
  - eval "$(ssh-agent -s)" #start the ssh agent
  - cat .secret-enc/github_key | openssl aes-256-cbc -a -d -k  "$PASSWORD" > github_key
  - chmod 600 github_key
  - ssh-add github_key
  - git push 
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls